---
title: "Codebook for HAR Project"
author: "Ng Tian Chyr"
date: "10/29/2021"
output: html_document
---

Fields of Variables:

activity
subject
timeBodyAcc.mean...X
timeBodyAcc.mean...Y
timeBodyAcc.mean...Z
timeBodyAcc.std...X
timeBodyAcc.std...Y
timeBodyAcc.std...Z
timeGravityAcc.mean...X
timeGravityAcc.mean...Y
timeGravityAcc.mean...Z
timeGravityAcc.std...X
timeGravityAcc.std...Y
timeGravityAcc.std...Z
timeBodyAccJerk.mean...X
timeBodyAccJerk.mean...Y
timeBodyAccJerk.mean...Z
timeBodyAccJerk.std...X
timeBodyAccJerk.std...Y
timeBodyAccJerk.std...Z
timeBodyGyro.mean...X
timeBodyGyro.mean...Y
timeBodyGyro.mean...Z
timeBodyGyro.std...X
timeBodyGyro.std...Y
timeBodyGyro.std...Z
timeBodyGyroJerk.mean...X
timeBodyGyroJerk.mean...Y
timeBodyGyroJerk.mean...Z
timeBodyGyroJerk.std...X
timeBodyGyroJerk.std...Y
timeBodyGyroJerk.std...Z
timeBodyAccMag.mean..
timeBodyAccMag.std..
timeGravityAccMag.mean..
timeGravityAccMag.std..
timeBodyAccJerkMag.mean..
timeBodyAccJerkMag.std..
timeBodyGyroMag.mean..
timeBodyGyroMag.std..
timeBodyGyroJerkMag.mean..
timeBodyGyroJerkMag.std..
freqBodyAcc.mean...X
freqBodyAcc.mean...Y
freqBodyAcc.mean...Z
freqBodyAcc.std...X
freqBodyAcc.std...Y
freqBodyAcc.std...Z
freqBodyAcc.meanFreq...X
freqBodyAcc.meanFreq...Y

